name: Build using .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nuget/setup-nuget@v1      
      with:
        nuget-version: '5.x'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Restore with NuGet (Jungle Helper)
      run: nuget restore *.sln

    - name: Build using Mono (Jungle Helper)
      run: msbuild *.sln "/p:Configuration=Debug"

    - name: Upload artifact (Jungle Helper)
      uses: actions/upload-artifact@v2
      with:
        name: JungleHelper
        path: Code/bin/Debug/JungleHelper.dll
        
    - name: Restore with NuGet (Into The Jungle Code Mod)
      run: nuget restore Z_IntoTheJungleCodeMod/*.sln

    - name: Build using Mono (Into The Jungle Code Mod)
      run: msbuild Z_IntoTheJungleCodeMod/*.sln "/p:Configuration=Debug"

    - name: Upload artifact (Into The Jungle Code Mod)
      uses: actions/upload-artifact@v2
      with:
        name: IntoTheJungleCodeMod
        path: Z_IntoTheJungleCodeMod/bin/Debug/IntoTheJungleCodeMod.dll

    - name: git fetch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        path: latest-repo

    - name: Publish release
      env:
        ZIPNAME: JungleHelper
        GITHUB_SHA: ${{ github.sha }}
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        # Does the commit message contain [ci skip]?
        msg=$(git log -n 1 "--format=%B" | head -n 1 | tr -d '\n')
        if [ "$(echo $msg | grep "\[ci skip\]")" != "" ]
        then
            echo "ci skip detected, skipping Discord hook"
            exit
        fi
        
        # Is the commit being build still the latest commit on the branch?
        if ((cd latest-repo && git rev-parse HEAD) | grep $GITHUB_SHA)
        then
            # Zip out the file, and send it to Discord.
            ZIPNAME=$ZIPNAME-${GITHUB_SHA:0:8}.zip
            PING=""
            zip -qq -r $ZIPNAME everest.yaml Code/bin/Debug/JungleHelper.dll Ahorn Graphics Audio Dialog MaxHelpingHandWipes DecalRegistry.xml
            url=$(curl -H 'Content-Type: multipart/form-data' -X POST -F "file=@$ZIPNAME" -F "content=$PING **New Jungle Helper update!**" "$DISCORD_WEBHOOK" | grep -Po 'cdn.discordapp.com\/.*?\.zip' | tr -d '\n')
            curl -H 'Content-Type: multipart/form-data' -X POST -F "file=@Z_IntoTheJungleCodeMod/bin/Debug/IntoTheJungleCodeMod.dll" "$DISCORD_WEBHOOK"
            curl -H 'Content-Type: application/json' -X POST -d "$(jq -n \
                --arg zipname "$ZIPNAME" \
                --arg url "$url" \
                --arg msg "$msg" \
                --arg change_embed "[Click here to see changes in this commit](https://github.com/max4805/JungleHelper/commit/$GITHUB_SHA)" \
                '{embeds: [{title: "Install \($zipname)", url: "https://0x0ade.ga/twoclick/?\($url)", description: $msg, fields: [{name: "Changes", value: $change_embed}]}]}' \
            )" "$DISCORD_WEBHOOK"
        else
            echo "current commit $GITHUB_SHA is not the latest commit on branch, skipping"
        fi